name: SaveNServe CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build and test backend
      run: |
        cd backend
        mvn clean package -DskipTests
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Build frontend
      run: |
        cd frontend
        npm ci
        npm run build
    
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Set up Docker Buildx
      if: github.ref == 'refs/heads/main'
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push backend Docker image
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/savenserve-backend:latest
    
    - name: Build and push frontend Docker image
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/savenserve-frontend:latest

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to AWS EC2
      run: |
        # Write the SSH key from secrets to a temporary file
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem

        # Copy deployment files to the server
        scp -o StrictHostKeyChecking=no -i private_key.pem \
          docker-compose.prod.yml \
          deploy.sh \
          ec2-user@${{ secrets.EC2_HOST }}:~/savenserve/
        
        # SSH into the server to install Docker, create .env, and run the deployment
        ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          # Install Docker and Docker Compose Plugin for Amazon Linux 2023
          sudo dnf update -y
          sudo dnf install docker -y
          sudo dnf install docker-compose-plugin -y
          
          # Add ec2-user to the docker group
          sudo usermod -aG docker ec2-user
          
          # Start the Docker service
          sudo systemctl enable docker
          sudo systemctl start docker
          
          # Change to the application directory
          cd ~/savenserve

          # Create the .env file securely on the server
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" > .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "EC2_HOST=${{ secrets.EC2_HOST }}" >> .env

          # Make the deployment script executable and run it WITH SUDO
          chmod +x deploy.sh
          sudo ./deploy.sh
        EOF